revive:
  build: .
  container_name: revive
  privileged: true
  restart: always
  ports:
    - "48654:80"
  volumes:
    - ./../server/nginx.conf:/etc/nginx/nginx.conf
    - ./entrypoint.sh:/usr/local/bin/entrypoint.sh
